const generalConstants = {
    STATUS_ACTIVE : 1,
    STATUS_INACTIVE:2,
    TRANSACTION_INCOME:1,
    TRANSACTION_EXPENDITURE:2,
    TRANSACTION_TRANSFER:3,
    TRANSACTION_SELL:4,
    TRANSACTION_DEVOLUTION:5
}

module.exports = generalConstants